---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "loan"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "loanapp"
  namespace: "loan"
  labels:
    app: "loanapp"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "loanapp"
  template:
    metadata:
      labels:
        app: "loanapp"
    spec:
      containers:
      - name: "loan-db-sha256-1"
        image: "gcr.io/gcpdemo-334906/github.com/divijasivada/loan-db@sha256:f88e4b59c34fbaa2db889b1d82603728cfc348bb5fd6ac19da76ae552b524cd7"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "loanapp-hpa-zwcj"
  namespace: "loan"
  labels:
    app: "loanapp"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "loanapp"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
